### ISSUE TITLE
Install API

### ISSUE THREAD

**Issue by Antonio19-jpg** [zealottormunds/ns4moddingapi#1]
Hello,
As the title says, how can I install the modding API?
Thank you

**Comment by zealottormunds** [comment]
How's it going? You can get the API from here:
https://github.com/zealottormunds/ns4moddingapi/releases/download/1.2b/Modding.API.v1.2b.rar
Put the extracted files in your Storm 4 root folder and you should be good.

By default, the API is configured for players instead of modders. This means that the modding console is disabled. To enable it, you need to edit the "config.ini" file located in "/Root folder of Naruto Storm 4/moddingapi/". Open the file and find the property called "EnableConsole=0". Set it as 1, and you're ready to go.

You can find all documentation in the API's wiki: https://github.com/zealottormunds/ns4moddingapi/wiki

**Comment by Antonio19-jpg** [comment]
Hi, I closed the issue because immediately after I found those files and managed to install it.
May I ask you how can I add a new character after expanding the characters slots?
Thank you

**Comment by zealottormunds** [comment]
Sorry for the huge delay lmao, I just noticed these issues.

Use this tutorial to add new characters: https://www.youtube.com/watch?v=Ll9WmOgJAEk

**Comment by Antonio19-jpg** [comment]
Thank you, I will check it out.
Also, I noticed that with the new DLC I had problems with the old mod. Is
there a way to fix this?


Il giorno lun 1 giu 2020 alle ore 07:56 Zealot Tormunds <
notifications@github.com> ha scritto:

**Comment by zealottormunds** [comment]
It depends on which mods, but yeah, there's a big chance that patch mods and certain others will have to be adapted by their authors to work on the newest version.

**Comment by Antonio19-jpg** [comment]
Ok thank you


Il giorno gio 4 giu 2020 alle ore 04:33 Zealot Tormunds <
notifications@github.com> ha scritto:
